const namespace = {
        strength: 'Strength',
        finesse: 'Finesse',
        intelligence: 'Intelligence',
        constitution: 'Constitution',
        memory: 'Memory',
        wits: 'Wits',

        dualWielding: 'Dual wielding',
        ranged: 'Ranged',
        singlehanded: 'Single-handed',
        twohanded: 'Two-handed',
        leadership: 'Leadership',
        perseverance: 'Perseverance',
        retribution: 'Retribution',
        aerothurge: 'Aerothurge',
        geomancer: 'Geomancer',
        huntsman: 'Huntsman',
        hydrosophist: 'Hydrosophist',
        necromancer: 'Necromancer',
        polymorph: 'Polymorph',
        pyrokinetic: 'Pyrokinetic',
        scoundrel: 'Scoundrel',
        summoning: 'Summoning',
        warfare: 'Warfare',

        bartering: 'Bartering',
        luckyCharm: 'Lucky charm',
        persuasion: 'Persuasion',
        loremaster: 'Loremaster',
        telekinesis: 'Telekinesis',
        sneaking: 'Sneaking',
        thievery: 'Thievery',

        AllSkilledUp: 'All skilled up',
        Ambidextrous: 'Ambidextrous',
        ArrowRecovery: 'Arrow recovery',
        BiggerAndBetter: 'Bigger and better',
        ComebackKid: 'Comeback kid',
        Demon: 'Daemon',
        DuckDuckGoose: 'Duck-duck-goose',
        ElementalAffinity: 'Elemental affinity',
        ElementalRanger: 'Elemental ranger',
        Escapist: 'Escapist',
        Executioner: 'Executioner',
        FarOutMan: 'Far-out-man',
        FiveStarDiner: 'Five-star diner',
        GlassCannon: 'Glass cannon',
        Guerilla: 'Guerilla',
        Hothead: 'Hothead',
        Ice_King: 'Ice king',
        Leech: 'Leech',
        LivingArmour: 'Living armour',
        LoneWolf: 'Lone wolf',
        Mnemonic: 'Mnemonic',
        MorningPerson: 'Morning person',
        Opportunist: 'Opportunist',
        ParryMaster: 'Parry master',
        PetPal: 'Pet pal',
        PictureofHealth: 'Picture of health',
        SavageSortilege: 'Savage sortilege',
        Slingshot: 'Slingshot',
        Stench: 'Stench',
        ThePawn: 'The pawn',
        Torturer: 'Torturer',
        Unstable: 'Unstable',
        WalkItOff: 'Walk it off',
        WhatARush: 'What a rush',

        health: 'Health',

        phArmor: 'Physical Armor',
        mArmor: 'Magic Armor',
        restorePhArmor: 'Physical Armor restoration',
        restoreMArmor: 'Magic armor restoration',
        restoreArmorFromStatus: 'Armor restored by status',

        strDmg: 'Strength damage',
        physDmg: 'Physical damage',
        SHDmg: 'Single-handed damage',
        THDmg: 'Two-handed damage',
        finDmg: 'Finesse damage',
        DWDmg: 'Dual wielding damage',
        RangedDmg: 'Ranged damage',
        SneakDmg: 'Sneaking damage',
        intDmg: 'Intelligence damage',
        PoisonDmg: 'Poison damage',
        FireDmg: 'Fire damage',
        reflectDmg: 'Retribution reflect damage',
        MADmg: 'Magic Armor damage',
        HGDmg: 'Damage from high ground',
        SummonDmg: 'Summoning damage',

        critChance: 'Critical chance',
        rangedCritChance: 'Ranged critical chance',
        critChanceFullHP: 'Critical chance at Full Health',
        critChanceMultiplier: 'Critical strike damage multiplier',
        THCritChanceMultiplier: 'Two-handed crit damage multiplier',

        baseAcc: 'Base accuracy',
        SHAcc: 'Single-handed accuracy',
        FullHPAcc: 'Accuracy at Full Health',

        dodge: 'Dodge',
        necroHealing: 'Healing from Necromancer',
        healingIncrease: 'Healing increase',

        fire: 'Fire resistance',
        water: 'Water resistance',
        earth: 'Earth resistance',
        air: 'Air resistance',
        poison: 'Poison resistance',

        initiative: 'Initiative',
        memorySlots: 'Memory slots',
        moveSpeed: 'Move speed',
        maxAP: 'Max action points',
        startAP: 'Start turn action points',
        turnAP: 'Each turn action points',
        moveWeight: 'Move weight',
        carryWeight: 'Carry weight'
};
export const getName = (key) => {
    return namespace[key]
};
export const getDescription = (key) => {
        return 'asfasfasf ldsanasdfnew asdfnsakjdnfkasjdnfkasjdnf as' +
            ' nfkajsdnfkjasdn jkans asd fnkajsdfn kjans'
};
export default getName;