const namespace = {
        strength: 'Strength',
        finesse: 'Finesse',
        intelligence: 'Intelligence',
        constitution: 'Constitution',
        memory: 'Memory',
        wits: 'Wits',

        dualWielding: 'Dual wielding',
        ranged: 'Ranged',
        singlehanded: 'Single-handed',
        twohanded: 'Two-handed',
        leadership: 'Leadership',
        perseverance: 'Perseverance',
        retribution: 'Retribution',
        aerothurge: 'Aerothurge',
        geomancer: 'Geomancer',
        huntsman: 'Huntsman',
        hydrosophist: 'Hydrosophist',
        necromancer: 'Necromancer',
        polymorph: 'Polymorph',
        pyrokinetic: 'Pyrokinetic',
        scoundrel: 'Scoundrel',
        summoning: 'Summoning',
        warfare: 'Warfare',

        bartering: 'Bartering',
        luckyCharm: 'Lucky charm',
        persuasion: 'Persuasion',
        loremaster: 'Loremaster',
        telekinesis: 'Telekinesis',
        sneaking: 'Sneaking',
        thievery: 'Thievery',

        AllSkilledUp: 'All skilled up',
        Ambidextrous: 'Ambidextrous',
        ArrowRecovery: 'Arrow recovery',
        BiggerAndBetter: 'Bigger and better',
        ComebackKid: 'Comeback kid',
        Demon: 'Daemon',
        DuckDuckGoose: 'Duck-duck-goose',
        ElementalAffinity: 'Elemental affinity',
        ElementalRanger: 'Elemental ranger',
        Escapist: 'Escapist',
        Executioner: 'Executioner',
        FarOutMan: 'Far-out-man',
        FiveStarDiner: 'Five-star diner',
        GlassCannon: 'Glass cannon',
        Guerilla: 'Guerilla',
        Hothead: 'Hothead',
        Ice_King: 'Ice king',
        Leech: 'Leech',
        LivingArmour: 'Living armour',
        LoneWolf: 'Lone wolf',
        Mnemonic: 'Mnemonic',
        MorningPerson: 'Morning person',
        Opportunist: 'Opportunist',
        ParryMaster: 'Parry master',
        PetPal: 'Pet pal',
        PictureofHealth: 'Picture of health',
        SavageSortilege: 'Savage sortilege',
        Slingshot: 'Slingshot',
        Stench: 'Stench',
        ThePawn: 'The pawn',
        Torturer: 'Torturer',
        Unstable: 'Unstable',
        WalkItOff: 'Walk it off',
        WhatARush: 'What a rush',
};
const getName = (key) => {
    return namespace[key]
};
export default getName;